### ISSUE TITLE
MCXboxBroadcast Extension Friend Managment On Bungeecord + Proxy Doesn't Works

### ISSUE THREAD

**Issue by XPaladiumyX** [rtm516/MCXboxBroadcast#83]
When someone add the bot as friend on a proxy server; the bot doesn't accept or remove friends
Here is my config: 
![Capture d’écran 2024-06-07 075952](https://github.com/rtm516/MCXboxBroadcast/assets/126415682/f90415cb-1aa5-43cd-a123-efbced9cd10c)
Also the MCXboxBroadcast reload extension make it crash and doesn't display anymore on the list until the server restart.

**Comment by XPaladiumyX** [comment]
> Please provide a full log file

Sure no problems sorry to answer only now i was busy ._.
[2024-06-07-1.log.gz](https://github.com/user-attachments/files/15743915/2024-06-07-1.log.gz)
[latest(2).zip](https://github.com/user-attachments/files/15743919/latest.2.zip)

Here you have the latest and one day before the restart
And i have this error while trying to dumpsession as you can see here.
![Capture d’écran 2024-06-07 210101](https://github.com/rtm516/MCXboxBroadcast/assets/126415682/06cb9687-4a81-44a2-9f65-bce0c0fd0ed9)

Here is the geyserdump if you need :
https://dump.geysermc.org/q5n5nSo74rgitDKHtLoJy6wdt7EDScLI

And here is the config or mcxboxbroadcast :

[archive-2024-06-07T190258Z.tar.gz](https://github.com/user-attachments/files/15743946/archive-2024-06-07T190258Z.tar.gz)

I think you have everything you need. 
Thank you for answering me, I just wanted to report this error because I don't think it comes from the configuration but from compatibility.

Sincerely, XPaladiumyX Dev.

**Comment by sennby** [comment]
same dumpsession error here, and seemingly have been through my troubleshooting steps on this aswell. I wish the  dev didnt close my issue and tell me its not an issue and its my fault...

**Comment by rtm516** [comment]
dumpsession should be fixed in the latest build

**Comment by XPaladiumyX** [comment]
> dumpsession should be fixed in the latest build

It seems not, i tested the latest build on the latest geysermc and /mcxboxbroadcast dumpsession doesn't works same error.

**Comment by rtm516** [comment]
> It seems not, i tested the latest build on the latest geysermc and /mcxboxbroadcast dumpsession doesn't works same error.

If its the exact same error then you haven't updated, if not then please share the error

https://github.com/rtm516/MCXboxBroadcast/releases/tag/20

**Comment by XPaladiumyX** [comment]
The friend auto accept still doesn't works, do you need a another log file or something else to be able to fix it?

**Comment by rtm516** [comment]
> The friend auto accept still doesn't works, do you need a another log file or something else to be able to fix it?

Can you provide the session dump?

**Comment by XPaladiumyX** [comment]
> > The friend auto accept still doesn't works, do you need a another log file or something else to be able to fix it?
> 
> Can you provide the session dump?
[archive-2024-06-09T165252Z.tar.gz](https://github.com/user-attachments/files/15753364/archive-2024-06-09T165252Z.tar.gz)
Here is the current and last session response

**Comment by XPaladiumyX** [comment]
> > The friend auto accept still doesn't works, do you need a another log file or something else to be able to fix it?
> 
> Can you provide the session dump?

![Capture d’écran 2024-06-11 140125](https://github.com/rtm516/MCXboxBroadcast/assets/126415682/2541af46-8888-41c8-aa78-622946e1cd80)
And i saw this error this morning
